-- Biptrix schema (spec §13). Every statement is idempotent; db/migrate.js
-- runs this file on boot and versioned ALTERs after it.
-- Conventions: TEXT ids generated by the app (core/util.js newId), ISO-8601
-- UTC timestamps written by the app (never SQL now(), so rqlite replays the
-- exact same values), 0/1 integers for booleans.

-- ---------------------------------------------------------------- identity

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL,                      -- canonical: trimmed, lower-case
  name TEXT NOT NULL,
  password_hash TEXT,
  totp_secret TEXT,                         -- base32, encrypted at rest
  platform_role TEXT,                       -- 'operator' or NULL
  status TEXT NOT NULL DEFAULT 'active',    -- active | disabled
  locale TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email);

CREATE TABLE IF NOT EXISTS sessions (
  id_hash TEXT PRIMARY KEY,                 -- sha256 of the cookie value
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  mfa_ok INTEGER NOT NULL DEFAULT 0,
  ip TEXT,
  user_agent TEXT,
  created_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);

-- Password reset and other single-use e-mail links (hash only).
CREATE TABLE IF NOT EXISTS email_tokens (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  purpose TEXT NOT NULL,
  token_hash TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_email_tokens_hash ON email_tokens(token_hash);

-- Passwordless sign-in: one-time codes sent by e-mail (hash only).
CREATE TABLE IF NOT EXISTS login_codes (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code_hash TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_login_codes_user ON login_codes(user_id, created_at);

-- Failed sign-in / OTP attempts per key, sliding window (credential stuffing).
CREATE TABLE IF NOT EXISTS auth_failures (
  key TEXT NOT NULL,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_auth_failures_key ON auth_failures(key, created_at);

-- ----------------------------------------------------------- organizations

CREATE TABLE IF NOT EXISTS organizations (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',    -- active | suspended
  plan TEXT NOT NULL DEFAULT 'pilot',
  max_members INTEGER NOT NULL DEFAULT 500,
  storage_quota_mb INTEGER NOT NULL DEFAULT 10240,
  brand_color TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_org_slug ON organizations(slug);

CREATE TABLE IF NOT EXISTS org_domains (
  org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  domain TEXT NOT NULL,
  verified_at TEXT,
  PRIMARY KEY (org_id, domain)
);

-- role: owner | admin | compliance | member | external
CREATE TABLE IF NOT EXISTS memberships (
  org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'member',
  status TEXT NOT NULL DEFAULT 'active',    -- active | revoked
  title TEXT,
  department TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (org_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_memberships_user ON memberships(user_id, status);

CREATE TABLE IF NOT EXISTS org_invites (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'member',
  token_hash TEXT NOT NULL,
  invited_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  expires_at TEXT NOT NULL,
  accepted_at TEXT,
  revoked_at TEXT,
  created_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_org_invites_token ON org_invites(token_hash);
CREATE INDEX IF NOT EXISTS idx_org_invites_org ON org_invites(org_id, created_at);

-- One row per organization; `version` increments on every change and is
-- copied into meetings (policy snapshot reference).
CREATE TABLE IF NOT EXISTS policies (
  org_id TEXT PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
  version INTEGER NOT NULL DEFAULT 1,
  data TEXT NOT NULL DEFAULT '{}',
  updated_by TEXT,
  updated_at TEXT NOT NULL
);

-- ---------------------------------------------------------------- messaging

-- type: dm | group | space. Spaces carry name/visibility; dm_key makes a DM
-- between two users unique per org.
CREATE TABLE IF NOT EXISTS conversations (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  name TEXT,
  description TEXT,
  visibility TEXT,                          -- space: public | private
  dm_key TEXT,
  created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  last_seq INTEGER NOT NULL DEFAULT 0,
  last_message_at TEXT,
  archived_at TEXT,
  created_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_conversations_dm ON conversations(org_id, dm_key) WHERE dm_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_conversations_org ON conversations(org_id, type);

-- role: member | moderator (Space Moderator)
CREATE TABLE IF NOT EXISTS conversation_members (
  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'member',
  last_read_seq INTEGER NOT NULL DEFAULT 0,
  muted INTEGER NOT NULL DEFAULT 0,
  joined_at TEXT NOT NULL,
  PRIMARY KEY (conversation_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_conversation_members_user ON conversation_members(user_id);

-- seq is the per-conversation order (spec §7.8); client_message_id makes a
-- retried send idempotent. kind: text | meeting | system.
CREATE TABLE IF NOT EXISTS messages (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  seq INTEGER NOT NULL,
  author_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  client_message_id TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'text',
  body TEXT NOT NULL DEFAULT '',
  meta TEXT,                                -- JSON, e.g. {"meeting_id": "..."}
  parent_id TEXT,
  reply_count INTEGER NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 1,
  pinned_at TEXT,
  pinned_by TEXT,
  edited_at TEXT,
  deleted_at TEXT,
  created_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_seq ON messages(conversation_id, seq);
CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_client ON messages(conversation_id, author_id, client_message_id);
CREATE INDEX IF NOT EXISTS idx_messages_org_time ON messages(org_id, created_at);
CREATE INDEX IF NOT EXISTS idx_messages_parent ON messages(parent_id) WHERE parent_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS message_mentions (
  message_id TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  conversation_id TEXT NOT NULL,
  seq INTEGER NOT NULL,
  PRIMARY KEY (message_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_mentions_user ON message_mentions(user_id, conversation_id, seq);

CREATE TABLE IF NOT EXISTS reactions (
  message_id TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  emoji TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (message_id, user_id, emoji)
);

-- Files are stored on disk/object storage under storage_key, never in the DB.
CREATE TABLE IF NOT EXISTS attachments (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  uploader_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  conversation_id TEXT REFERENCES conversations(id) ON DELETE CASCADE,
  message_id TEXT REFERENCES messages(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  mime TEXT NOT NULL,
  size INTEGER NOT NULL,
  sha256 TEXT NOT NULL,
  storage_key TEXT NOT NULL,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_attachments_message ON attachments(message_id);
CREATE INDEX IF NOT EXISTS idx_attachments_conversation ON attachments(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_attachments_org ON attachments(org_id);

-- Stored files whose attachment row is gone (message deleted, retention,
-- conversation removed). Filled by a trigger, so no deletion path can skip
-- it; the maintenance job unlinks the bytes and clears the row.
CREATE TABLE IF NOT EXISTS file_deletions (
  storage_key TEXT PRIMARY KEY,
  created_at TEXT NOT NULL
);
CREATE TRIGGER IF NOT EXISTS attachments_file_cleanup AFTER DELETE ON attachments BEGIN
  INSERT OR IGNORE INTO file_deletions (storage_key, created_at) VALUES (old.storage_key, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));
END;

-- Full-text search over message bodies (external content, kept in sync by
-- triggers so both SQLite and rqlite maintain it on every write).
CREATE VIRTUAL TABLE IF NOT EXISTS messages_fts USING fts5(
  body, content='messages', content_rowid='rowid', tokenize='unicode61 remove_diacritics 2'
);
CREATE TRIGGER IF NOT EXISTS messages_fts_ai AFTER INSERT ON messages BEGIN
  INSERT INTO messages_fts(rowid, body) VALUES (new.rowid, new.body);
END;
CREATE TRIGGER IF NOT EXISTS messages_fts_ad AFTER DELETE ON messages BEGIN
  INSERT INTO messages_fts(messages_fts, rowid, body) VALUES ('delete', old.rowid, old.body);
END;
CREATE TRIGGER IF NOT EXISTS messages_fts_au AFTER UPDATE OF body ON messages BEGIN
  INSERT INTO messages_fts(messages_fts, rowid, body) VALUES ('delete', old.rowid, old.body);
  INSERT INTO messages_fts(rowid, body) VALUES (new.rowid, new.body);
END;

-- Durable event log / outbox (spec §11–12). id is monotonic; clients resume
-- from their last id (system.sync), other Node instances poll it.
-- Scope: a conversation (delivered to its members) or one user.
CREATE TABLE IF NOT EXISTS events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  org_id TEXT NOT NULL,
  conversation_id TEXT,
  user_id TEXT,
  type TEXT NOT NULL,
  data TEXT NOT NULL,
  node_id TEXT NOT NULL,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_org ON events(org_id, id);

-- ----------------------------------------------------------------- meetings

-- state: scheduled | open | live | ended | canceled
CREATE TABLE IF NOT EXISTS meetings (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  conversation_id TEXT REFERENCES conversations(id) ON DELETE SET NULL,
  host_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  state TEXT NOT NULL,
  scheduled_at TEXT,
  duration_min INTEGER NOT NULL DEFAULT 60,
  expires_at TEXT NOT NULL,
  lobby_for_members INTEGER NOT NULL DEFAULT 0,
  policy_version INTEGER NOT NULL DEFAULT 1,
  policy_snapshot TEXT NOT NULL DEFAULT '{}',
  started_at TEXT,
  ended_at TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_meetings_org ON meetings(org_id, state, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_meetings_conversation ON meetings(conversation_id);

-- Internal invitees (user_id) and external invitees (email + hashed token).
CREATE TABLE IF NOT EXISTS meeting_invitations (
  id TEXT PRIMARY KEY,
  meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  org_id TEXT NOT NULL,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  email TEXT,
  name TEXT,
  token_hash TEXT,
  invited_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  expires_at TEXT NOT NULL,
  verified_at TEXT,
  revoked_at TEXT,
  created_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_meeting_invitations_token ON meeting_invitations(token_hash) WHERE token_hash IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_meeting_invitations_meeting ON meeting_invitations(meeting_id);
CREATE INDEX IF NOT EXISTS idx_meeting_invitations_org_day ON meeting_invitations(org_id, created_at);

-- One-time e-mail codes for guests (hash only, attempts counted).
CREATE TABLE IF NOT EXISTS email_otps (
  id TEXT PRIMARY KEY,
  invitation_id TEXT NOT NULL REFERENCES meeting_invitations(id) ON DELETE CASCADE,
  code_hash TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_email_otps_invitation ON email_otps(invitation_id, created_at);

-- Guest join sessions: bound to one invitation and one meeting.
CREATE TABLE IF NOT EXISTS guest_sessions (
  id_hash TEXT PRIMARY KEY,
  invitation_id TEXT NOT NULL REFERENCES meeting_invitations(id) ON DELETE CASCADE,
  meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  revoked_at TEXT,
  created_at TEXT NOT NULL
);

-- state: lobby | admitted | rejected | left | removed
CREATE TABLE IF NOT EXISTS meeting_participants (
  id TEXT PRIMARY KEY,
  meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  invitation_id TEXT REFERENCES meeting_invitations(id) ON DELETE CASCADE,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'participant', -- host | cohost | participant | guest
  state TEXT NOT NULL,
  joined_at TEXT,
  left_at TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_meeting_participants_meeting ON meeting_participants(meeting_id, state);
CREATE UNIQUE INDEX IF NOT EXISTS idx_meeting_participants_user ON meeting_participants(meeting_id, user_id) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_meeting_participants_invitation ON meeting_participants(meeting_id, invitation_id) WHERE invitation_id IS NOT NULL;

-- -------------------------------------------------------------------- audit

-- Append-only: the application never updates or deletes audit rows.
CREATE TABLE IF NOT EXISTS audit_events (
  id TEXT PRIMARY KEY,
  org_id TEXT,
  actor_id TEXT,
  actor_label TEXT,
  action TEXT NOT NULL,
  resource_type TEXT,
  resource_id TEXT,
  data TEXT,
  ip TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_org_time ON audit_events(org_id, created_at);

-- Per-tenant usage counters for operations and billing (spec §16).
CREATE TABLE IF NOT EXISTS usage_counters (
  org_id TEXT NOT NULL,
  period TEXT NOT NULL,                     -- YYYY-MM
  metric TEXT NOT NULL,
  value INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (org_id, period, metric)
);

CREATE TABLE IF NOT EXISTS schema_migrations (
  version INTEGER PRIMARY KEY,
  applied_at TEXT NOT NULL
);
